using UnityEngine;
using Pinyin4net;
using System;
using System.Collections.Generic;

// https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/processor/baker.py

public static class Baker
{
    private static bool isZh(char word) => !char.IsPunctuation(word) && char.GetUnicodeCategory(word) == System.Globalization.UnicodeCategory.OtherLetter;
    private static bool ShouldKeepSymbol(char symbol) => symbol != '_' && symbol != '~' && Convert.ToUInt16(symbol) != 8203;

    public static List<string> Parse(ref string text)
    {
        List<string> pinyinStr = new List<string>();

        foreach (char c in text)
        {
            if (!ShouldKeepSymbol(c))
                continue;

            if (c == ' ')
                pinyinStr.Add("#0");
            else if (isZh(c))
                pinyinStr.Add(PinyinHelper.ToHanyuPinyinStringArray(c)[0]);
            else
                pinyinStr.Add("#");
        }

        return pinyinStr;
    }

    public static List<string> GetPhonemeFromCharAndPinyin(string cnChars, List<string> pinyin)
    {
        cnChars = cnChars.Replace("#4", "");
        int charLen = cnChars.Length;
        int i = 0, j = 0;
        List<string> result = new List<string>() { };

        while (i < charLen)
        {
            char curChar = cnChars[i];
            if (isZh(curChar))
            {
                if (!PinyinDict.ContainsKey(pinyin[j].Substring(0, pinyin[j].Length - 1)))
                {
                    // Debug.Assert(cnChars[i + 1] == '儿' || cnChars[i + 1] == '兒');
                    Debug.Assert(pinyin[j][pinyin[j].Length - 2] == 'r');
                    string tone = pinyin[j][pinyin[j].Length - 1].ToString();
                    string a = pinyin[j].Substring(0, pinyin[j].Length - 2);
                    string a1 = PinyinDict[a][0];
                    string a2 = PinyinDict[a][1];
                    result.Add(a1);
                    result.Add(a2 + tone);
                    result.Add("er5");
                    if (i + 2 < charLen && cnChars[i + 2] != '#')
                    {
                        result.Add("#0");
                    }
                    i += 2;
                    j += 1;
                }
                else
                {
                    string tone = pinyin[j][pinyin[j].Length - 1].ToString();
                    string a = pinyin[j].Substring(0, pinyin[j].Length - 1);
                    string a1 = PinyinDict[a][0];
                    string a2 = PinyinDict[a][1];
                    result.Add(a1);
                    result.Add(a2 + tone);
                    if (i + 1 < charLen && cnChars[i + 1] != '#')
                    {
                        result.Add("#0");
                    }
                    i += 1;
                    j += 1;
                }
            }
            else if (curChar == '#')
            {
                result.Add(cnChars.Substring(i, 2));
                i += 2;
            }
            else
            {
                // ignore the unknown char and punctuation
                // result.Add(curChar.ToString());
                i += 1;
            }
        }
        if (result[result.Count - 1] == "#0")
        {
            result.RemoveAt(result.Count - 1);
        }
        //result.Add("sil");
        Debug.Assert(j == pinyin.Count);
        return result;
    }

    public static Dictionary<string, int> Symbol_to_ID = new Dictionary<string, int> {
       {"pad", 0},
       {"sil", 1},
       {"#0", 2},
       {"#1", 3},
       {"#2", 4},
       {"#3", 5},
       {"^", 6},
       {"b", 7},
       {"c", 8},
       {"ch", 9},
       {"d", 10},
       {"f", 11},
       {"g", 12},
       {"h", 13},
       {"j", 14},
       {"k", 15},
       {"l", 16},
       {"m", 17},
       {"n", 18},
       {"p", 19},
       {"q", 20},
       {"r", 21},
       {"s", 22},
       {"sh", 23},
       {"t", 24},
       {"x", 25},
       {"z", 26},
       {"zh", 27},
       {"a1", 28},
       {"a2", 29},
       {"a3", 30},
       {"a4", 31},
       {"a5", 32},
       {"ai1", 33},
       {"ai2", 34},
       {"ai3", 35},
       {"ai4", 36},
       {"ai5", 37},
       {"an1", 38},
       {"an2", 39},
       {"an3", 40},
       {"an4", 41},
       {"an5", 42},
       {"ang1", 43},
       {"ang2", 44},
       {"ang3", 45},
       {"ang4", 46},
       {"ang5", 47},
       {"ao1", 48},
       {"ao2", 49},
       {"ao3", 50},
       {"ao4", 51},
       {"ao5", 52},
       {"e1", 53},
       {"e2", 54},
       {"e3", 55},
       {"e4", 56},
       {"e5", 57},
       {"ei1", 58},
       {"ei2", 59},
       {"ei3", 60},
       {"ei4", 61},
       {"ei5", 62},
       {"en1", 63},
       {"en2", 64},
       {"en3", 65},
       {"en4", 66},
       {"en5", 67},
       {"eng1", 68},
       {"eng2", 69},
       {"eng3", 70},
       {"eng4", 71},
       {"eng5", 72},
       {"er1", 73},
       {"er2", 74},
       {"er3", 75},
       {"er4", 76},
       {"er5", 77},
       {"i1", 78},
       {"i2", 79},
       {"i3", 80},
       {"i4", 81},
       {"i5", 82},
       {"ia1", 83},
       {"ia2", 84},
       {"ia3", 85},
       {"ia4", 86},
       {"ia5", 87},
       {"ian1", 88},
       {"ian2", 89},
       {"ian3", 90},
       {"ian4", 91},
       {"ian5", 92},
       {"iang1", 93},
       {"iang2", 94},
       {"iang3", 95},
       {"iang4", 96},
       {"iang5", 97},
       {"iao1", 98},
       {"iao2", 99},
       {"iao3", 100},
       {"iao4", 101},
       {"iao5", 102},
       {"ie1", 103},
       {"ie2", 104},
       {"ie3", 105},
       {"ie4", 106},
       {"ie5", 107},
       {"ii1", 108},
       {"ii2", 109},
       {"ii3", 110},
       {"ii4", 111},
       {"ii5", 112},
       {"iii1", 113},
       {"iii2", 114},
       {"iii3", 115},
       {"iii4", 116},
       {"iii5", 117},
       {"in1", 118},
       {"in2", 119},
       {"in3", 120},
       {"in4", 121},
       {"in5", 122},
       {"ing1", 123},
       {"ing2", 124},
       {"ing3", 125},
       {"ing4", 126},
       {"ing5", 127},
       {"iong1", 128},
       {"iong2", 129},
       {"iong3", 130},
       {"iong4", 131},
       {"iong5", 132},
       {"iou1", 133},
       {"iou2", 134},
       {"iou3", 135},
       {"iou4", 136},
       {"iou5", 137},
       {"o1", 138},
       {"o2", 139},
       {"o3", 140},
       {"o4", 141},
       {"o5", 142},
       {"ong1", 143},
       {"ong2", 144},
       {"ong3", 145},
       {"ong4", 146},
       {"ong5", 147},
       {"ou1", 148},
       {"ou2", 149},
       {"ou3", 150},
       {"ou4", 151},
       {"ou5", 152},
       {"u1", 153},
       {"u2", 154},
       {"u3", 155},
       {"u4", 156},
       {"u5", 157},
       {"ua1", 158},
       {"ua2", 159},
       {"ua3", 160},
       {"ua4", 161},
       {"ua5", 162},
       {"uai1", 163},
       {"uai2", 164},
       {"uai3", 165},
       {"uai4", 166},
       {"uai5", 167},
       {"uan1", 168},
       {"uan2", 169},
       {"uan3", 170},
       {"uan4", 171},
       {"uan5", 172},
       {"uang1", 173},
       {"uang2", 174},
       {"uang3", 175},
       {"uang4", 176},
       {"uang5", 177},
       {"uei1", 178},
       {"uei2", 179},
       {"uei3", 180},
       {"uei4", 181},
       {"uei5", 182},
       {"uen1", 183},
       {"uen2", 184},
       {"uen3", 185},
       {"uen4", 186},
       {"uen5", 187},
       {"ueng1", 188},
       {"ueng2", 189},
       {"ueng3", 190},
       {"ueng4", 191},
       {"ueng5", 192},
       {"uo1", 193},
       {"uo2", 194},
       {"uo3", 195},
       {"uo4", 196},
       {"uo5", 197},
       {"v1", 198},
       {"v2", 199},
       {"v3", 200},
       {"v4", 201},
       {"v5", 202},
       {"van1", 203},
       {"van2", 204},
       {"van3", 205},
       {"van4", 206},
       {"van5", 207},
       {"ve1", 208},
       {"ve2", 209},
       {"ve3", 210},
       {"ve4", 211},
       {"ve5", 212},
       {"vn1", 213},
       {"vn2", 214},
       {"vn3", 215},
       {"vn4", 216},
       {"vn5", 217},
       {"eos", 218 } };

    private static Dictionary<string, string[]> PinyinDict = new Dictionary<string, string[]>{
       {"a", new string[]{"^","a" } },
       {"ai", new string[] {"^","ai" }},
       {"an", new string[] {"^","an" }},
       {"ang", new string[] {"^","ang" }},
       {"ao", new string[] {"^","ao" }},
       {"ba", new string[] {"b","a" }},
       {"bai", new string[] {"b","ai" }},
       {"ban", new string[] {"b","an" }},
       {"bang", new string[] {"b","ang" }},
       {"bao", new string[] {"b","ao" }},
       {"be", new string[] {"b","e" }},
       {"bei", new string[] {"b","ei" }},
       {"ben", new string[] {"b","en" }},
       {"beng", new string[] {"b","eng" }},
       {"bi", new string[] {"b","i" }},
       {"bian", new string[] {"b","ian" }},
       {"biao", new string[] {"b","iao" }},
       {"bie", new string[] {"b","ie" }},
       {"bin", new string[] {"b","in" }},
       {"bing", new string[] {"b","ing" }},
       {"bo", new string[] {"b","o" }},
       {"bu", new string[] {"b","u" }},
       {"ca", new string[] {"c","a" }},
       {"cai", new string[] {"c","ai" }},
       {"can", new string[] {"c","an" }},
       {"cang", new string[] {"c","ang" }},
       {"cao", new string[] {"c","ao" }},
       {"ce", new string[] {"c","e" }},
       {"cen", new string[] {"c","en" }},
       {"ceng", new string[] {"c","eng" }},
       {"cha", new string[] {"ch","a" }},
       {"chai", new string[] {"ch","ai" }},
       {"chan", new string[] {"ch","an" }},
       {"chang", new string[] {"ch","ang" }},
       {"chao", new string[] {"ch","ao" }},
       {"che", new string[] {"ch","e" }},
       {"chen", new string[] {"ch","en" }},
       {"cheng", new string[] {"ch","eng" }},
       {"chi", new string[] {"ch","iii" }},
       {"chong", new string[] {"ch","ong" }},
       {"chou", new string[] {"ch","ou" }},
       {"chu", new string[] {"ch","u" }},
       {"chua", new string[] {"ch","ua" }},
       {"chuai", new string[] {"ch","uai" }},
       {"chuan", new string[] {"ch","uan" }},
       {"chuang", new string[] {"ch","uang" }},
       {"chui", new string[] {"ch","uei" }},
       {"chun", new string[] {"ch","uen" }},
       {"chuo", new string[] {"ch","uo" }},
       {"ci", new string[] {"c","ii" }},
       {"cong", new string[] {"c","ong" }},
       {"cou", new string[] {"c","ou" }},
       {"cu", new string[] {"c","u" }},
       {"cuan", new string[] {"c","uan" }},
       {"cui", new string[] {"c","uei" }},
       {"cun", new string[] {"c","uen" }},
       {"cuo", new string[] {"c","uo" }},
       {"da", new string[] {"d","a" }},
       {"dai", new string[] {"d","ai" }},
       {"dan", new string[] {"d","an" }},
       {"dang", new string[] {"d","ang" }},
       {"dao", new string[] {"d","ao" }},
       {"de", new string[] {"d","e" }},
       {"dei", new string[] {"d","ei" }},
       {"den", new string[] {"d","en" }},
       {"deng", new string[] {"d","eng" }},
       {"di", new string[] {"d","i" }},
       {"dia", new string[] {"d","ia" }},
       {"dian", new string[] {"d","ian" }},
       {"diao", new string[] {"d","iao" }},
       {"die", new string[] {"d","ie" }},
       {"ding", new string[] {"d","ing" }},
       {"diu", new string[] {"d","iou" }},
       {"dong", new string[] {"d","ong" }},
       {"dou", new string[] {"d","ou" }},
       {"du", new string[] {"d","u" }},
       {"duan", new string[] {"d","uan" }},
       {"dui", new string[] {"d","uei" }},
       {"dun", new string[] {"d","uen" }},
       {"duo", new string[] {"d","uo" }},
       {"e", new string[] {"^","e" }},
       {"ei", new string[] {"^","ei" }},
       {"en", new string[] {"^","en" }},
       {"ng", new string[] {"^","en" }},
       {"eng", new string[] {"^","eng" }},
       {"er", new string[] {"^","er" }},
       {"fa", new string[] {"f","a" }},
       {"fan", new string[] {"f","an" }},
       {"fang", new string[] {"f","ang" }},
       {"fei", new string[] {"f","ei" }},
       {"fen", new string[] {"f","en" }},
       {"feng", new string[] {"f","eng" }},
       {"fo", new string[] {"f","o" }},
       {"fou", new string[] {"f","ou" }},
       {"fu", new string[] {"f","u" }},
       {"ga", new string[] {"g","a" }},
       {"gai", new string[] {"g","ai" }},
       {"gan", new string[] {"g","an" }},
       {"gang", new string[] {"g","ang" }},
       {"gao", new string[] {"g","ao" }},
       {"ge", new string[] {"g","e" }},
       {"gei", new string[] {"g","ei" }},
       {"gen", new string[] {"g","en" }},
       {"geng", new string[] {"g","eng" }},
       {"gong", new string[] {"g","ong" }},
       {"gou", new string[] {"g","ou" }},
       {"gu", new string[] {"g","u" }},
       {"gua", new string[] {"g","ua" }},
       {"guai", new string[] {"g","uai" }},
       {"guan", new string[] {"g","uan" }},
       {"guang", new string[] {"g","uang" }},
       {"gui", new string[] {"g","uei" }},
       {"gun", new string[] {"g","uen" }},
       {"guo", new string[] {"g","uo" }},
       {"ha", new string[] {"h","a" }},
       {"hai", new string[] {"h","ai" }},
       {"han", new string[] {"h","an" }},
       {"hang", new string[] {"h","ang" }},
       {"hao", new string[] {"h","ao" }},
       {"he", new string[] {"h","e" }},
       {"hei", new string[] {"h","ei" }},
       {"hen", new string[] {"h","en" }},
       {"heng", new string[] {"h","eng" }},
       {"hong", new string[] {"h","ong" }},
       {"hou", new string[] {"h","ou" }},
       {"hu", new string[] {"h","u" }},
       {"hua", new string[] {"h","ua" }},
       {"huai", new string[] {"h","uai" }},
       {"huan", new string[] {"h","uan" }},
       {"huang", new string[] {"h","uang" }},
       {"hui", new string[] {"h","uei" }},
       {"hun", new string[] {"h","uen" }},
       {"huo", new string[] {"h","uo" }},
       {"ji", new string[] {"j","i" }},
       {"jia", new string[] {"j","ia" }},
       {"jian", new string[] {"j","ian" }},
       {"jiang", new string[] {"j","iang" }},
       {"jiao", new string[] {"j","iao" }},
       {"jie", new string[] {"j","ie" }},
       {"jin", new string[] {"j","in" }},
       {"jing", new string[] {"j","ing" }},
       {"jiong", new string[] {"j","iong" }},
       {"jiu", new string[] {"j","iou" }},
       {"ju", new string[] {"j","v" }},
       {"juan", new string[] {"j","van" }},
       {"jue", new string[] {"j","ve" }},
       {"jun", new string[] {"j","vn" }},
       {"ka", new string[] {"k","a" }},
       {"kai", new string[] {"k","ai" }},
       {"kan", new string[] {"k","an" }},
       {"kang", new string[] {"k","ang" }},
       {"kao", new string[] {"k","ao" }},
       {"ke", new string[] {"k","e" }},
       {"kei", new string[] {"k","ei" }},
       {"ken", new string[] {"k","en" }},
       {"keng", new string[] {"k","eng" }},
       {"kong", new string[] {"k","ong" }},
       {"kou", new string[] {"k","ou" }},
       {"ku", new string[] {"k","u" }},
       {"kua", new string[] {"k","ua" }},
       {"kuai", new string[] {"k","uai" }},
       {"kuan", new string[] {"k","uan" }},
       {"kuang", new string[] {"k","uang" }},
       {"kui", new string[] {"k","uei" }},
       {"kun", new string[] {"k","uen" }},
       {"kuo", new string[] {"k","uo" }},
       {"la", new string[] {"l","a" }},
       {"lai", new string[] {"l","ai" }},
       {"lan", new string[] {"l","an" }},
       {"lang", new string[] {"l","ang" }},
       {"lao", new string[] {"l","ao" }},
       {"le", new string[] {"l","e" }},
       {"lei", new string[] {"l","ei" }},
       {"leng", new string[] {"l","eng" }},
       {"li", new string[] {"l","i" }},
       {"lia", new string[] {"l","ia" }},
       {"lian", new string[] {"l","ian" }},
       {"liang", new string[] {"l","iang" }},
       {"liao", new string[] {"l","iao" }},
       {"lie", new string[] {"l","ie" }},
       {"lin", new string[] {"l","in" }},
       {"ling", new string[] {"l","ing" }},
       {"liu", new string[] {"l","iou" }},
       {"lo", new string[] {"l","o" }},
       {"long", new string[] {"l","ong" }},
       {"lou", new string[] {"l","ou" }},
       {"lu", new string[] {"l","u" }},
       {"lv", new string[] {"l","v" }},
       {"luan", new string[] {"l","uan" }},
       {"lve", new string[] {"l","ve" }},
       {"lue", new string[] {"l","ve" }},
       {"lun", new string[] {"l","uen" }},
       {"luo", new string[] {"l","uo" }},
       {"ma", new string[] {"m","a" }},
       {"mai", new string[] {"m","ai" }},
       {"man", new string[] {"m","an" }},
       {"mang", new string[] {"m","ang" }},
       {"mao", new string[] {"m","ao" }},
       {"me", new string[] {"m","e" }},
       {"mei", new string[] {"m","ei" }},
       {"men", new string[] {"m","en" }},
       {"meng", new string[] {"m","eng" }},
       {"mi", new string[] {"m","i" }},
       {"mian", new string[] {"m","ian" }},
       {"miao", new string[] {"m","iao" }},
       {"mie", new string[] {"m","ie" }},
       {"min", new string[] {"m","in" }},
       {"ming", new string[] {"m","ing" }},
       {"miu", new string[] {"m","iou" }},
       {"mo", new string[] {"m","o" }},
       {"mou", new string[] {"m","ou" }},
       {"mu", new string[] {"m","u" }},
       {"na", new string[] {"n","a" }},
       {"nai", new string[] {"n","ai" }},
       {"nan", new string[] {"n","an" }},
       {"nang", new string[] {"n","ang" }},
       {"nao", new string[] {"n","ao" }},
       {"ne", new string[] {"n","e" }},
       {"nei", new string[] {"n","ei" }},
       {"nen", new string[] {"n","en" }},
       {"neng", new string[] {"n","eng" }},
       {"ni", new string[] {"n","i" }},
       {"nia", new string[] {"n","ia" }},
       {"nian", new string[] {"n","ian" }},
       {"niang", new string[] {"n","iang" }},
       {"niao", new string[] {"n","iao" }},
       {"nie", new string[] {"n","ie" }},
       {"nin", new string[] {"n","in" }},
       {"ning", new string[] {"n","ing" }},
       {"niu", new string[] {"n","iou" }},
       {"nong", new string[] {"n","ong" }},
       {"nou", new string[] {"n","ou" }},
       {"nu", new string[] {"n","u" }},
       {"nv", new string[] {"n","v" }},
       {"nuan", new string[] {"n","uan" }},
       {"nve", new string[] {"n","ve" }},
       {"nue", new string[] {"n","ve" }},
       {"nuo", new string[] {"n","uo" }},
       {"o", new string[] {"^","o" }},
       {"ou", new string[] {"^","ou" }},
       {"pa", new string[] {"p","a" }},
       {"pai", new string[] {"p","ai" }},
       {"pan", new string[] {"p","an" }},
       {"pang", new string[] {"p","ang" }},
       {"pao", new string[] {"p","ao" }},
       {"pe", new string[] {"p","e" }},
       {"pei", new string[] {"p","ei" }},
       {"pen", new string[] {"p","en" }},
       {"peng", new string[] {"p","eng" }},
       {"pi", new string[] {"p","i" }},
       {"pian", new string[] {"p","ian" }},
       {"piao", new string[] {"p","iao" }},
       {"pie", new string[] {"p","ie" }},
       {"pin", new string[] {"p","in" }},
       {"ping", new string[] {"p","ing" }},
       {"po", new string[] {"p","o" }},
       {"pou", new string[] {"p","ou" }},
       {"pu", new string[] {"p","u" }},
       {"qi", new string[] {"q","i" }},
       {"qia", new string[] {"q","ia" }},
       {"qian", new string[] {"q","ian" }},
       {"qiang", new string[] {"q","iang" }},
       {"qiao", new string[] {"q","iao" }},
       {"qie", new string[] {"q","ie" }},
       {"qin", new string[] {"q","in" }},
       {"qing", new string[] {"q","ing" }},
       {"qiong", new string[] {"q","iong" }},
       {"qiu", new string[] {"q","iou" }},
       {"qu", new string[] {"q","v" }},
       {"quan", new string[] {"q","van" }},
       {"que", new string[] {"q","ve" }},
       {"qun", new string[] {"q","vn" }},
       {"ran", new string[] {"r","an" }},
       {"rang", new string[] {"r","ang" }},
       {"rao", new string[] {"r","ao" }},
       {"re", new string[] {"r","e" }},
       {"ren", new string[] {"r","en" }},
       {"reng", new string[] {"r","eng" }},
       {"ri", new string[] {"r","iii" }},
       {"rong", new string[] {"r","ong" }},
       {"rou", new string[] {"r","ou" }},
       {"ru", new string[] {"r","u" }},
       {"rua", new string[] {"r","ua" }},
       {"ruan", new string[] {"r","uan" }},
       {"rui", new string[] {"r","uei" }},
       {"run", new string[] {"r","uen" }},
       {"ruo", new string[] {"r","uo" }},
       {"sa", new string[] {"s","a" }},
       {"sai", new string[] {"s","ai" }},
       {"san", new string[] {"s","an" }},
       {"sang", new string[] {"s","ang" }},
       {"sao", new string[] {"s","ao" }},
       {"se", new string[] {"s","e" }},
       {"sen", new string[] {"s","en" }},
       {"seng", new string[] {"s","eng" }},
       {"sha", new string[] {"sh","a" }},
       {"shai", new string[] {"sh","ai" }},
       {"shan", new string[] {"sh","an" }},
       {"shang", new string[] {"sh","ang" }},
       {"shao", new string[] {"sh","ao" }},
       {"she", new string[] {"sh","e" }},
       {"shei", new string[] {"sh","ei" }},
       {"shen", new string[] {"sh","en" }},
       {"sheng", new string[] {"sh","eng" }},
       {"shi", new string[] {"sh","iii" }},
       {"shou", new string[] {"sh","ou" }},
       {"shu", new string[] {"sh","u" }},
       {"shua", new string[] {"sh","ua" }},
       {"shuai", new string[] {"sh","uai" }},
       {"shuan", new string[] {"sh","uan" }},
       {"shuang", new string[] {"sh","uang" }},
       {"shui", new string[] {"sh","uei" }},
       {"shun", new string[] {"sh","uen" }},
       {"shuo", new string[] {"sh","uo" }},
       {"si", new string[] {"s","ii" }},
       {"song", new string[] {"s","ong" }},
       {"sou", new string[] {"s","ou" }},
       {"su", new string[] {"s","u" }},
       {"suan", new string[] {"s","uan" }},
       {"sui", new string[] {"s","uei" }},
       {"sun", new string[] {"s","uen" }},
       {"suo", new string[] {"s","uo" }},
       {"ta", new string[] {"t","a" }},
       {"tai", new string[] {"t","ai" }},
       {"tan", new string[] {"t","an" }},
       {"tang", new string[] {"t","ang" }},
       {"tao", new string[] {"t","ao" }},
       {"te", new string[] {"t","e" }},
       {"tei", new string[] {"t","ei" }},
       {"teng", new string[] {"t","eng" }},
       {"ti", new string[] {"t","i" }},
       {"tian", new string[] {"t","ian" }},
       {"tiao", new string[] {"t","iao" }},
       {"tie", new string[] {"t","ie" }},
       {"ting", new string[] {"t","ing" }},
       {"tong", new string[] {"t","ong" }},
       {"tou", new string[] {"t","ou" }},
       {"tu", new string[] {"t","u" }},
       {"tuan", new string[] {"t","uan" }},
       {"tui", new string[] {"t","uei" }},
       {"tun", new string[] {"t","uen" }},
       {"tuo", new string[] {"t","uo" }},
       {"wa", new string[] {"^","ua" }},
       {"wai", new string[] {"^","uai" }},
       {"wan", new string[] {"^","uan" }},
       {"wang", new string[] {"^","uang" }},
       {"wei", new string[] {"^","uei" }},
       {"wen", new string[] {"^","uen" }},
       {"weng", new string[] {"^","ueng" }},
       {"wo", new string[] {"^","uo" }},
       {"wu", new string[] {"^","u" }},
       {"xi", new string[] {"x","i" }},
       {"xia", new string[] {"x","ia" }},
       {"xian", new string[] {"x","ian" }},
       {"xiang", new string[] {"x","iang" }},
       {"xiao", new string[] {"x","iao" }},
       {"xie", new string[] {"x","ie" }},
       {"xin", new string[] {"x","in" }},
       {"xing", new string[] {"x","ing" }},
       {"xiong", new string[] {"x","iong" }},
       {"xiu", new string[] {"x","iou" }},
       {"xu", new string[] {"x","v" }},
       {"xuan", new string[] {"x","van" }},
       {"xue", new string[] {"x","ve" }},
       {"xun", new string[] {"x","vn" }},
       {"ya", new string[] {"^","ia" }},
       {"yan", new string[] {"^","ian" }},
       {"yang", new string[] {"^","iang" }},
       {"yao", new string[] {"^","iao" }},
       {"ye", new string[] {"^","ie" }},
       {"yi", new string[] {"^","i" }},
       {"yin", new string[] {"^","in" }},
       {"ying", new string[] {"^","ing" }},
       {"yo", new string[] {"^","iou" }},
       {"yong", new string[] {"^","iong" }},
       {"you", new string[] {"^","iou" }},
       {"yu", new string[] {"^","v" }},
       {"yuan", new string[] {"^","van" }},
       {"yue", new string[] {"^","ve" }},
       {"yun", new string[] {"^","vn" }},
       {"za", new string[] {"z","a" }},
       {"zai", new string[] {"z","ai" }},
       {"zan", new string[] {"z","an" }},
       {"zang", new string[] {"z","ang" }},
       {"zao", new string[] {"z","ao" }},
       {"ze", new string[] {"z","e" }},
       {"zei", new string[] {"z","ei" }},
       {"zen", new string[] {"z","en" }},
       {"zeng", new string[] {"z","eng" }},
       {"zha", new string[] {"zh","a" }},
       {"zhai", new string[] {"zh","ai" }},
       {"zhan", new string[] {"zh","an" }},
       {"zhang", new string[] {"zh","ang" }},
       {"zhao", new string[] {"zh","ao" }},
       {"zhe", new string[] {"zh","e" }},
       {"zhei", new string[] {"zh","ei" }},
       {"zhen", new string[] {"zh","en" }},
       {"zheng", new string[] {"zh","eng" }},
       {"zhi", new string[] {"zh","iii" }},
       {"zhong", new string[] {"zh","ong" }},
       {"zhou", new string[] {"zh","ou" }},
       {"zhu", new string[] {"zh","u" }},
       {"zhua", new string[] {"zh","ua" }},
       {"zhuai", new string[] {"zh","uai" }},
       {"zhuan", new string[] {"zh","uan" }},
       {"zhuang", new string[] {"zh","uang" }},
       {"zhui", new string[] {"zh","uei" }},
       {"zhun", new string[] {"zh","uen" }},
       {"zhuo", new string[] {"zh","uo" }},
       {"zi", new string[] {"z","ii" }},
       {"zong", new string[] {"z","ong" }},
       {"zou", new string[] {"z","ou" }},
       {"zu", new string[] {"z","u" }},
       {"zuan", new string[] {"z","uan" }},
       {"zui", new string[] {"z","uei" }},
       {"zun", new string[] {"z","uen" }},
       {"zuo", new string[] {"z","uo" } } };
}